// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-T3BDWT-kuTW27E_Q4V5LHUqGMGTG-s',
    appId: '1:561451497081:web:d5cdff498d0826041146a8',
    messagingSenderId: '561451497081',
    projectId: 'fooddelivery-3c2de',
    authDomain: 'fooddelivery-3c2de.firebaseapp.com',
    storageBucket: 'fooddelivery-3c2de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9f6Y5XnE2Dwxtr9A6U0Eie0rHe7bpmjs',
    appId: '1:561451497081:android:74f986150963313a1146a8',
    messagingSenderId: '561451497081',
    projectId: 'fooddelivery-3c2de',
    storageBucket: 'fooddelivery-3c2de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdtojPNN3to802Z-t6JZOzkjLMyDalMw8',
    appId: '1:561451497081:ios:0ab65aff2120c3ab1146a8',
    messagingSenderId: '561451497081',
    projectId: 'fooddelivery-3c2de',
    storageBucket: 'fooddelivery-3c2de.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdtojPNN3to802Z-t6JZOzkjLMyDalMw8',
    appId: '1:561451497081:ios:0ab65aff2120c3ab1146a8',
    messagingSenderId: '561451497081',
    projectId: 'fooddelivery-3c2de',
    storageBucket: 'fooddelivery-3c2de.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-T3BDWT-kuTW27E_Q4V5LHUqGMGTG-s',
    appId: '1:561451497081:web:05fbc579bfa8d0181146a8',
    messagingSenderId: '561451497081',
    projectId: 'fooddelivery-3c2de',
    authDomain: 'fooddelivery-3c2de.firebaseapp.com',
    storageBucket: 'fooddelivery-3c2de.firebasestorage.app',
  );

}